// <auto-generated />
using System;
using GabrovoUltraWebApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GabrovoUltraWebApp.Infrastructure.Migrations
{
    [DbContext(typeof(GabrovoUltraContext))]
    [Migration("20240417171930_seed more users and results")]
    partial class seedmoreusersandresults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GabrovoUltraWebApp.Infrastructure.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxAge")
                        .HasColumnType("int");

                    b.Property<int>("MinAge")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxAge = 21,
                            MinAge = 16,
                            Name = "Юнуша",
                            RaceId = 1
                        },
                        new
                        {
                            Id = 2,
                            MaxAge = 35,
                            MinAge = 22,
                            Name = "Младши",
                            RaceId = 1
                        },
                        new
                        {
                            Id = 3,
                            MaxAge = 49,
                            MinAge = 36,
                            Name = "Старши",
                            RaceId = 1
                        },
                        new
                        {
                            Id = 4,
                            MaxAge = 100,
                            MinAge = 50,
                            Name = "Ветеран",
                            RaceId = 1
                        },
                        new
                        {
                            Id = 5,
                            MaxAge = 21,
                            MinAge = 16,
                            Name = "Юнуша",
                            RaceId = 2
                        },
                        new
                        {
                            Id = 6,
                            MaxAge = 35,
                            MinAge = 22,
                            Name = "Младши",
                            RaceId = 2
                        },
                        new
                        {
                            Id = 7,
                            MaxAge = 49,
                            MinAge = 36,
                            Name = "Старши",
                            RaceId = 2
                        },
                        new
                        {
                            Id = 8,
                            MaxAge = 100,
                            MinAge = 50,
                            Name = "Ветеран",
                            RaceId = 2
                        });
                });

            modelBuilder.Entity("GabrovoUltraWebApp.Infrastructure.Data.Models.Distance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("PrimaryKey");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasComment("Description of the distance");

                    b.Property<double>("ElevationGain")
                        .HasColumnType("float")
                        .HasComment("Elevation gain of the distance in meters");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Length")
                        .HasColumnType("float")
                        .HasComment("Length of the distance in kilometers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the distance");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasComment("Start time of the distance");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("Distances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "75км с 4300 D+ и пълна автономност - без никакви подрекрепителни пунктве. Истинско изпитание.",
                            ElevationGain = 4300.0,
                            ImagePath = "/Components/Distances/trqnva1.jpg",
                            Length = 75.0,
                            Name = "Черешката",
                            RaceId = 1,
                            StartTime = "06:09"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Маратонски 42км с над 2500 D+ и пълна автономност - без никакви подрекрепителни пунктве. По-малкото \"мъчение\".",
                            ElevationGain = 2500.0,
                            ImagePath = "/Components/Distances/kodja-kaq.jpg",
                            Length = 42.0,
                            Name = "Глазурата",
                            RaceId = 1,
                            StartTime = "08:00"
                        },
                        new
                        {
                            Id = 3,
                            Description = "30км Sky с 1950 D+ и пълна автономност - без никакви подрекрепителни пунктве. Предизвикателството.",
                            ElevationGain = 1950.0,
                            ImagePath = "/Components/Distances/tarnovo.jpg",
                            Length = 30.0,
                            Name = "Блатът",
                            RaceId = 1,
                            StartTime = "09:30"
                        },
                        new
                        {
                            Id = 4,
                            Description = "14км с 1050 D+ и пълна автономност - без никакви подрекрепителни пунктве. Напреднало ниво.",
                            ElevationGain = 1050.0,
                            ImagePath = "/Components/Distances/trqnva1.jpg",
                            Length = 14.0,
                            Name = "Жилката",
                            RaceId = 1,
                            StartTime = "12:00"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Скоростно изкачване на Телевизионната кула (Градище) 3.6км с 500 D+. Допълнително изпитание, в което всеки може да се включи.",
                            ElevationGain = 50.0,
                            ImagePath = "/Components/Distances/trqnva1.jpg",
                            Length = 5.0,
                            Name = "Допълнителен десерт",
                            RaceId = 1,
                            StartTime = "14:00"
                        });
                });

            modelBuilder.Entity("GabrovoUltraWebApp.Infrastructure.Data.Models.HeroSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("HeroSections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "nqkakav si tam lorem ipsum",
                            ImageUrl = "/public/VititeSkaliView.jpg",
                            Name = "Vitite skali view"
                        },
                        new
                        {
                            Id = 2,
                            Description = "gotina magla koqto ne se vijda na snimkata",
                            ImageUrl = "/public/Integra2.jpg",
                            Name = "Integral view 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Super qkiq deskription!",
                            ImageUrl = "/public/Integral.jpg",
                            Name = "Integral"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Super qkiq motivacionen citat",
                            ImageUrl = "/public/Skali.jpg",
                            Name = "Samo skali"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Malko kofti snimka",
                            ImageUrl = "/public/GradishteSunSet.jpg",
                            Name = "Gradishte"
                        },
                        new
                        {
                            Id = 6,
                            Description = "snimano na greshnata strana",
                            ImageUrl = "/public/IspolinSunset.jpg",
                            Name = "Ispolin"
                        });
                });

            modelBuilder.Entity("GabrovoUltraWebApp.Infrastructure.Data.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("PrimaryKey");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasComment("Description of the race");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Location of the race");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the race");

                    b.HasKey("Id");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Второ издание на невероятното трейл приключение",
                            Location = "Габрово",
                            Name = "Габрово Ултра 2024"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2023, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Първото първо по рода си трейл състезание в Габрово",
                            Location = "Габрово",
                            Name = "Габрово Ултра 2023"
                        });
                });

            modelBuilder.Entity("GabrovoUltraWebApp.Infrastructure.Data.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Registration Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistanceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaymentConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartingNumber")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Foreign key to ASPUsers");

                    b.HasKey("Id");

                    b.HasIndex("DistanceId");

                    b.HasIndex("RaceId");

                    b.ToTable("Registrations");

                    b.HasData(
                        new
                        {
                            Id = 12,
                            DistanceId = 2,
                            IsPaymentConfirmed = true,
                            RaceId = 1,
                            RegistrationDate = new DateTime(2024, 4, 17, 20, 19, 25, 957, DateTimeKind.Local).AddTicks(3230),
                            StartingNumber = "7505",
                            UserId = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f36"
                        },
                        new
                        {
                            Id = 13,
                            DistanceId = 2,
                            IsPaymentConfirmed = true,
                            RaceId = 1,
                            RegistrationDate = new DateTime(2024, 4, 17, 20, 19, 25, 957, DateTimeKind.Local).AddTicks(3245),
                            StartingNumber = "7505",
                            UserId = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f37"
                        },
                        new
                        {
                            Id = 14,
                            DistanceId = 2,
                            IsPaymentConfirmed = true,
                            RaceId = 1,
                            RegistrationDate = new DateTime(2024, 4, 17, 20, 19, 25, 957, DateTimeKind.Local).AddTicks(3247),
                            StartingNumber = "7605",
                            UserId = "c6bc76d0-9af8-44ee-a228-55fb932fa1f37"
                        },
                        new
                        {
                            Id = 15,
                            DistanceId = 2,
                            IsPaymentConfirmed = true,
                            RaceId = 1,
                            RegistrationDate = new DateTime(2024, 4, 17, 20, 19, 25, 957, DateTimeKind.Local).AddTicks(3250),
                            StartingNumber = "7506",
                            UserId = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f38"
                        },
                        new
                        {
                            Id = 16,
                            DistanceId = 2,
                            IsPaymentConfirmed = true,
                            RaceId = 1,
                            RegistrationDate = new DateTime(2024, 4, 17, 20, 19, 25, 957, DateTimeKind.Local).AddTicks(3252),
                            StartingNumber = "7507",
                            UserId = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f39"
                        },
                        new
                        {
                            Id = 17,
                            DistanceId = 2,
                            IsPaymentConfirmed = true,
                            RaceId = 1,
                            RegistrationDate = new DateTime(2024, 4, 17, 20, 19, 25, 957, DateTimeKind.Local).AddTicks(3254),
                            StartingNumber = "7508",
                            UserId = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f41"
                        },
                        new
                        {
                            Id = 18,
                            DistanceId = 4,
                            IsPaymentConfirmed = true,
                            RaceId = 1,
                            RegistrationDate = new DateTime(2024, 4, 17, 20, 19, 25, 957, DateTimeKind.Local).AddTicks(3257),
                            StartingNumber = "7509",
                            UserId = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f42"
                        },
                        new
                        {
                            Id = 19,
                            DistanceId = 2,
                            IsPaymentConfirmed = true,
                            RaceId = 1,
                            RegistrationDate = new DateTime(2024, 4, 17, 20, 19, 25, 957, DateTimeKind.Local).AddTicks(3259),
                            StartingNumber = "7510",
                            UserId = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f43"
                        },
                        new
                        {
                            Id = 20,
                            DistanceId = 3,
                            IsPaymentConfirmed = true,
                            RaceId = 1,
                            RegistrationDate = new DateTime(2024, 4, 17, 20, 19, 25, 957, DateTimeKind.Local).AddTicks(3262),
                            StartingNumber = "7511",
                            UserId = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f44"
                        },
                        new
                        {
                            Id = 21,
                            DistanceId = 4,
                            IsPaymentConfirmed = true,
                            RaceId = 1,
                            RegistrationDate = new DateTime(2024, 4, 17, 20, 19, 25, 957, DateTimeKind.Local).AddTicks(3264),
                            StartingNumber = "7512",
                            UserId = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f45"
                        },
                        new
                        {
                            Id = 22,
                            DistanceId = 4,
                            IsPaymentConfirmed = true,
                            RaceId = 1,
                            RegistrationDate = new DateTime(2024, 4, 17, 20, 19, 25, 957, DateTimeKind.Local).AddTicks(3267),
                            StartingNumber = "7513",
                            UserId = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f46"
                        });
                });

            modelBuilder.Entity("GabrovoUltraWebApp.Infrastructure.Data.Models.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryRank")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("FinishTme")
                        .HasColumnType("time");

                    b.Property<int>("OverallRank")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId")
                        .IsUnique();

                    b.ToTable("Results");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            CategoryRank = 0,
                            FinishTme = new TimeSpan(0, 3, 30, 0, 0),
                            OverallRank = 0,
                            RegistrationId = 12
                        },
                        new
                        {
                            Id = 12,
                            CategoryRank = 0,
                            FinishTme = new TimeSpan(0, 3, 45, 0, 0),
                            OverallRank = 0,
                            RegistrationId = 13
                        },
                        new
                        {
                            Id = 13,
                            CategoryRank = 0,
                            FinishTme = new TimeSpan(0, 3, 50, 0, 0),
                            OverallRank = 0,
                            RegistrationId = 14
                        },
                        new
                        {
                            Id = 14,
                            CategoryRank = 0,
                            FinishTme = new TimeSpan(0, 3, 55, 0, 0),
                            OverallRank = 0,
                            RegistrationId = 15
                        },
                        new
                        {
                            Id = 15,
                            CategoryRank = 0,
                            FinishTme = new TimeSpan(0, 4, 0, 0, 0),
                            OverallRank = 0,
                            RegistrationId = 16
                        },
                        new
                        {
                            Id = 16,
                            CategoryRank = 0,
                            FinishTme = new TimeSpan(0, 4, 5, 0, 0),
                            OverallRank = 0,
                            RegistrationId = 17
                        },
                        new
                        {
                            Id = 17,
                            CategoryRank = 0,
                            FinishTme = new TimeSpan(0, 4, 10, 0, 0),
                            OverallRank = 0,
                            RegistrationId = 18
                        },
                        new
                        {
                            Id = 18,
                            CategoryRank = 0,
                            FinishTme = new TimeSpan(0, 4, 15, 0, 0),
                            OverallRank = 0,
                            RegistrationId = 19
                        },
                        new
                        {
                            Id = 19,
                            CategoryRank = 0,
                            FinishTme = new TimeSpan(0, 4, 20, 0, 0),
                            OverallRank = 0,
                            RegistrationId = 20
                        },
                        new
                        {
                            Id = 20,
                            CategoryRank = 0,
                            FinishTme = new TimeSpan(0, 4, 25, 0, 0),
                            OverallRank = 0,
                            RegistrationId = 21
                        },
                        new
                        {
                            Id = 21,
                            CategoryRank = 0,
                            FinishTme = new TimeSpan(0, 4, 30, 0, 0),
                            OverallRank = 0,
                            RegistrationId = 22
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "80908387-bbd3-404f-a019-90f77d87adf8",
                            ConcurrencyStamp = "80908387-bbd3-404f-a019-90f77d87adf8",
                            Name = "Reader",
                            NormalizedName = "READER"
                        },
                        new
                        {
                            Id = "4be6dd46-69ab-4c08-a820-bcb4bb3d2922",
                            ConcurrencyStamp = "4be6dd46-69ab-4c08-a820-bcb4bb3d2922",
                            Name = "Writer",
                            NormalizedName = "WRITER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f36",
                            RoleId = "80908387-bbd3-404f-a019-90f77d87adf8"
                        },
                        new
                        {
                            UserId = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f37",
                            RoleId = "80908387-bbd3-404f-a019-90f77d87adf8"
                        },
                        new
                        {
                            UserId = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f40",
                            RoleId = "4be6dd46-69ab-4c08-a820-bcb4bb3d2922"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GabrovoUltraWebApp.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasComment("Age of the runner");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("City of origin");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Country of origin");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("FirstName of the runner");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasComment("Gender of the runner");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("LastName of the runner");

                    b.Property<int?>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("Team")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the team");

                    b.HasIndex("RegistrationId")
                        .IsUnique()
                        .HasFilter("[RegistrationId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f36",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "318cf0dc-6647-4c7a-a03d-bb7256521b0b",
                            Email = "pesho@gabrovoultra.bg",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "PESHO@GABROVOULTRA.BG",
                            NormalizedUserName = "PESHO@GABROVOULTRA.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEE0PpCp5+DYqluxxCF/69U5FjC69gaab/UC+4iNetZDRm265dYcKSW12hSTY0CdRig==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "03847e0f-d2e1-4302-b1eb-ab0a909e48d6",
                            TwoFactorEnabled = false,
                            UserName = "pesho@gabrovoultra.bg",
                            Age = 0,
                            City = "Gabrovo",
                            Country = "Bulgaria",
                            FirstName = "Pesho",
                            Gender = 0,
                            LastName = "Peshov",
                            RegistrationId = 12
                        },
                        new
                        {
                            Id = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f37",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4c689085-d420-40da-8d31-c7f13a2a9a6c",
                            Email = "sasho@gabrovoultra.bg",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SASHO@GABROVOULTRA>BG",
                            NormalizedUserName = "SASHO@GABROVOULTRA>BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEHSJmnWeyaYm92vp5/ZLGsmbp6vWYtC0uAgVk/oFykczWvARsTuUBtwbXgHq/7x1tw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "df755e15-a989-4fab-aa06-e4a137a91488",
                            TwoFactorEnabled = false,
                            UserName = "sasho@gabrovoultra.bg",
                            Age = 0,
                            City = "Gabrovo",
                            Country = "Bulgaria",
                            FirstName = "Sasho",
                            Gender = 0,
                            LastName = "Sashov",
                            RegistrationId = 13
                        },
                        new
                        {
                            Id = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f38",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "89fd66c5-4a34-4eef-b58c-1e6cc94e196c",
                            Email = "dimitrichko@gabrovoultra.bg",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DIMITRICHKO@GABROVOULTRA.BG",
                            NormalizedUserName = "DIMITRICHKO@GABROVOULTRA.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAENaejHFNfwPSE6ZxKanRNe74Km1DzZhdMbyykGuC3oJUvIAweeYfbprb5fm+fuBQ2g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cff8d8b8-aaf3-4ce1-ac98-7142762b44e6",
                            TwoFactorEnabled = false,
                            UserName = "dimitrichko@gabrovoultra.bg",
                            Age = 0,
                            City = "Dimitrovgrad",
                            Country = "Bulgaria",
                            FirstName = "Dimitrichko",
                            Gender = 0,
                            LastName = "Dimitrichkov",
                            RegistrationId = 15
                        },
                        new
                        {
                            Id = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f39",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "57e051f3-601b-4ff1-8f61-199451f81f2e",
                            Email = "filip@gabrovoultra.bg",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "FILIP@GABROVOULTRA.BG",
                            NormalizedUserName = "FILIP@GABROVOULTRA.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEK+6mSX7/JP3IG7PVyUJpA9M7SbwmOq2m2Muynfq6CLA0NmiwTtJkc//95GaJNu4Ww==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b49067a2-40b0-48d6-8034-db81cdf8abd5",
                            TwoFactorEnabled = false,
                            UserName = "filip@gabrovoultra.bg",
                            Age = 0,
                            City = "Veliko Tarnovo",
                            Country = "Bulgaria",
                            FirstName = "Filip",
                            Gender = 0,
                            LastName = "Filipov",
                            RegistrationId = 16
                        },
                        new
                        {
                            Id = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f40",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3844d1b3-02ff-41d0-a054-f9861b216484",
                            Email = "admin@gabrovoultra.bg",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GABROVOULTRA.BG",
                            NormalizedUserName = "ADMIN@GABROVOULTRA.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEAmf0rKNufN+9WRa7/pkQb4mhPq9sfpmCPHd6QhTTL9ZS1SHaayx2ihQM2Er3oCeFA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8e10ea2a-4472-4dd4-a094-eb0cfe42dd08",
                            TwoFactorEnabled = false,
                            UserName = "admin@gabrovoultra.bg",
                            Age = 0,
                            City = "Adminovgrad",
                            Country = "Bulgaria",
                            FirstName = "Admin",
                            Gender = 0,
                            LastName = "Adminov"
                        },
                        new
                        {
                            Id = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f41",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "33e0f7aa-3157-45be-9f2e-53c4dc86e013",
                            Email = "ivan@gabrovoultra.bg",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "IVAN@GABROVOULTRA.BG",
                            NormalizedUserName = "IVAN@GABROVOULTRA.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEP8wojNg3cLBzIDsjFix8qCQw9Vew9qu8oc5MuNV9OEE9dwOo1XGXvxl1C/xw/AKPg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2b603e69-1ba1-45fe-bad3-9e30ac70d4fa",
                            TwoFactorEnabled = false,
                            UserName = "ivan@gabrovoultra.bg",
                            Age = 0,
                            City = "Ivanovgrad",
                            Country = "Bulgaria",
                            FirstName = "Ivan",
                            Gender = 0,
                            LastName = "Ivanov",
                            RegistrationId = 17
                        },
                        new
                        {
                            Id = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f42",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1428cb70-9bf5-4fe4-a872-7c89447582ce",
                            Email = "stefan@gabrovoultra.bg",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "STEFAN@GABROVOULTRA.BG",
                            NormalizedUserName = "STEFAN@GABROVOULTRA.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAENej2TPCrfkEz8b9gylNfock49p89mtcwT2H70xbNqy89AleBE076XTnlrPWgpbhyQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1a7d4546-1c32-47ae-ba40-60935fecf4b1",
                            TwoFactorEnabled = false,
                            UserName = "stefan@gabrovoultra.bg",
                            Age = 0,
                            City = "Stefanovgrad",
                            Country = "Bulgaria",
                            FirstName = "Stefan",
                            Gender = 0,
                            LastName = "Stefanov",
                            RegistrationId = 18
                        },
                        new
                        {
                            Id = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f43",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dd0c361a-74c5-4681-9824-9d4acc07f583",
                            Email = "miroslav@gabrovoultra.bg",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MIROSLAV@GABROVOULTRA.BG",
                            NormalizedUserName = "MIROSLAV@GABROVOULTRA.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEOInUiAcTusfADatAmTxtVd3/HHsyRKUIao4tr95at0HUQ8Q/waOEpa3w8s7OHPspA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "59996d96-0e21-4b1c-858d-f33c110939d7",
                            TwoFactorEnabled = false,
                            UserName = "miroslav@gabrovoultra.bg",
                            Age = 0,
                            City = "Miroslavovgrad",
                            Country = "Bulgaria",
                            FirstName = "Miroslav",
                            Gender = 0,
                            LastName = "Miroslavov",
                            RegistrationId = 19
                        },
                        new
                        {
                            Id = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f44",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aa35f414-badc-4a49-8f83-e3e0525cd91d",
                            Email = "svetoslav@gabrovoultra.bg",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SVETOSLAV@GABROVOULTRA.BG",
                            NormalizedUserName = "SVETOSLAV@GABROVOULTRA.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAED5BmFAGSZS0SYzhPQoYYhrVHuke0me9WPhvBZ3gmlQLdYcNh2GGZ+vRgD6LUhKJBQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "96d11234-580e-4f0f-837a-4c34f57ed3f4",
                            TwoFactorEnabled = false,
                            UserName = "svetoslav@gabrovoultra.bg",
                            Age = 0,
                            City = "Svetoslavovgrad",
                            Country = "Bulgaria",
                            FirstName = "Svetoslav",
                            Gender = 0,
                            LastName = "Svetoslavov",
                            RegistrationId = 20
                        },
                        new
                        {
                            Id = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f45",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "583d4642-a1cd-4bee-9f48-946d72680963",
                            Email = "mihael@gabrovoultra.bg",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MIHAEL@GABROVOULTRA.BG",
                            NormalizedUserName = "MIHAEL@GABROVOULTRA.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEJYEg1bVuJibtQiwB4RlZIOhaf8tYvj1g8HN+mVOwL167iRrS9BnAVP62BUCc5fFwA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fae43a01-2ca1-4e37-9826-a03110ef7606",
                            TwoFactorEnabled = false,
                            UserName = "mihael@gabrovoultra.bg",
                            Age = 0,
                            City = "Gabrovo",
                            Country = "Bulgaria",
                            FirstName = "Mihael",
                            Gender = 0,
                            LastName = "Yordanov",
                            RegistrationId = 21
                        },
                        new
                        {
                            Id = "c6bc76d0-9af8-44ee-a228-55fb9bfa1f46",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b18a313f-bc4e-4670-8f0d-190e2782795a",
                            Email = "svetoslava@gabrovoultra.bg",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SVETOSLAVA@GABROVOULTRA.BG",
                            NormalizedUserName = "SVETOSLAVA@GABROVOULTRA.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAED1K5LkoXomjfn2pf8tX0M5dbDVegyvZwW2CcvrJa8xir03F0A2RIQ0bNoXWpeBong==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7262f669-2029-47b9-a454-92f12ed98a94",
                            TwoFactorEnabled = false,
                            UserName = "svetoslava@gabrovoultra.bg",
                            Age = 0,
                            City = "Gabrovo",
                            Country = "Bulgaria",
                            FirstName = "Svetoslava",
                            Gender = 0,
                            LastName = "Tsankova",
                            RegistrationId = 22
                        });
                });

            modelBuilder.Entity("GabrovoUltraWebApp.Infrastructure.Data.Models.Category", b =>
                {
                    b.HasOne("GabrovoUltraWebApp.Infrastructure.Data.Models.Race", "Race")
                        .WithMany("Categories")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("GabrovoUltraWebApp.Infrastructure.Data.Models.Distance", b =>
                {
                    b.HasOne("GabrovoUltraWebApp.Infrastructure.Data.Models.Race", "Race")
                        .WithMany("Distances")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("GabrovoUltraWebApp.Infrastructure.Data.Models.Registration", b =>
                {
                    b.HasOne("GabrovoUltraWebApp.Infrastructure.Data.Models.Distance", "Distance")
                        .WithMany("Registrations")
                        .HasForeignKey("DistanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GabrovoUltraWebApp.Infrastructure.Data.Models.Race", "Race")
                        .WithMany("Registrations")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distance");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("GabrovoUltraWebApp.Infrastructure.Data.Models.Result", b =>
                {
                    b.HasOne("GabrovoUltraWebApp.Infrastructure.Data.Models.Registration", "Registration")
                        .WithOne("Result")
                        .HasForeignKey("GabrovoUltraWebApp.Infrastructure.Data.Models.Result", "RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GabrovoUltraWebApp.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.HasOne("GabrovoUltraWebApp.Infrastructure.Data.Models.Registration", "Registration")
                        .WithOne("User")
                        .HasForeignKey("GabrovoUltraWebApp.Infrastructure.Data.Models.ApplicationUser", "RegistrationId");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("GabrovoUltraWebApp.Infrastructure.Data.Models.Distance", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("GabrovoUltraWebApp.Infrastructure.Data.Models.Race", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Distances");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("GabrovoUltraWebApp.Infrastructure.Data.Models.Registration", b =>
                {
                    b.Navigation("Result")
                        .IsRequired();

                    b.Navigation("User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
